#=================================================
# Description: Build Android HAL and dhd packages using GitHub Actions
# Lisence: MIT
# Author: 0312birdzhang
#=================================================

name: Build SailfishOS dhd

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:

  build:
    runs-on: ubuntu-20.04

    env:
      DEVICE: ginkgo
      VENDOR: xiaomi
      ANDROID_ROOT: /home/runner/work/hadk_16.0/
      SAILFISH_SKD_VERSION: 4.5.0.16

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        python git openjdk-8-jdk android-tools-adb bc bison \
        build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses-dev \
        lib32readline-dev lib32z1-dev  liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev \
        libtinfo5 libncurses5


    - name: Download repo bin file
      run: |
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "BirdZhang"
        git config --global user.email "0312birdzhang@gmail.com"

    - name: Downloading source code
      run: |
        source hadk.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        python3 ~/bin/repo init -u https://github.com/mer-hybris/android.git -b hybris-16.0 --depth=1
        python3 ~/bin/repo sync -j$(nproc --all) -c --no-clone-bundle --no-tags --optimized-fetch --prune

    - name: Check free disk
      run: |
        df -h
      shell: bash

    - name: Clone device spec source
      run: |
        source hadk.env
        git clone https://github.com/sailfish-on-ginkgo/device_xiaomi_ginkgo.git $ANDROID_ROOT/device/xiaomi/ginkgo --depth=1 --single-branch
        git clone https://github.com/sailfish-on-ginkgo/vendor_xiaomi_ginkgo.git $ANDROID_ROOT/vendor/xiaomi/ginkgo --depth=1 --single-branch
        git clone https://github.com/sailfish-on-ginkgo/kernel_xiaomi_ginkgo.git $ANDROID_ROOT/kernel/xiaomi/ginkgo --depth=1 --single-branch
        rm -rf $ANDROID_ROOT/hybris/hybris-boot
        git clone https://github.com/sailfish-on-ginkgo/hybris-boot.git  $ANDROID_ROOT/hybris/hybris-boot --depth=1
        git clone --recurse-submodules https://github.com/sailfish-on-ginkgo/droid-hal-ginkgo.git $ANDROID_ROOT/rpm --depth=1
        git clone --recurse-submodules https://github.com/sailfish-on-ginkgo/droid-config-ginkgo.git $ANDROID_ROOT/hybris/droid-configs --depth=1
        git clone --recurse-submodules https://github.com/sailfish-on-ginkgo/droid-hal-version-ginkgo.git $ANDROID_ROOT/hybris/droid-hal-version-ginkgo --depth=1
        git clone --recurse-submodules https://github.com/sailfish-on-ginkgo/hybris-installer $ANDROID_ROOT/hybris/hybris-installer --depth=1

    - name: Build HAL
      run: |
        chmod +x build-hal.sh
        bash build-hal.sh
      shell: bash

    - name: Build dhd in container
      run: |
        echo "clean more folders"
        rm -rf $ANDROID_ROOT/prebuilts $ANDROID_ROOT/external/chromium* $ANDROID_ROOT/tools/external/gradle $ANDROID_ROOT/packages
        rm -rf $ANDROID_ROOT/out/build-lineage_davinci.ninja
        chmod +x build-rpm.sh
        sudo docker images|grep -v REPOSITORY|awk '{print $3}'|xargs docker rmi
        sudo docker pull sailfishos-platform-sdk-aarch64:$SAILFISH_SKD_VERSION
        sudo docker run -v /home/runner/work:/home/nemo/work sailfishos-platform-sdk-aarch64:$SAILFISH_SKD_VERSION /bin/sh /home/nemo/work/ci/ci/build-rpm.sh
      shell: bash

    - name: Check free disk
      if: failure()
      run: |
        df -h
      shell: bash

    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: hybris-boot.img
        path: ${{env.ANDROID_ROOT}}/out/target/product/${{env.DEVICE}}/hybris-boot.img

    - name : Upload droid-local-repo
      uses: actions/upload-artifact@master
      with:
        name: droid-local-repo
        path: ${{env.ANDROID_ROOT}}/droid-local-repo
